name: chatty_widget
description: A simple Flutter widget that shows message in chat box on tap event.
version: 0.0.1
homepage: https://github.com/hyobbb/chatty_widget


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

